Repository taerakim/miniRT, pull requests merged in 2024-06, with the labels that each got.

#5 Feat: 구조체 추가
  .gitignore
  src/manda/include/struct.h
  src/manda/parse.c
Labels: feat

#6 Feat: 구조체 추가 및 변환함수, 기초 파싱기능 추가
  include/libft.h
  include_make/Variable.mk
  lib/Makefile
  lib/get_next_line/Makefile
  lib/get_next_line/get_next_line.c
  lib/get_next_line/get_next_line.h
  lib/get_next_line/get_next_line_utils.c
  lib/libft/Makefile
  lib/libft/get_next_line.c
  lib/libft/get_next_line_utils.c
  lib/libft/libft.h
  src/manda/Makefile
  src/manda/convertor.c
  src/manda/include/rt_struct.h
  src/manda/parse.c
  src/manda/parse.h
Labels: build, feat

#7 Feat: 파싱기능 업데이트
  lib/libft/ft_atoi.c
  lib/libft/ft_strlen.c
  src/manda/Makefile
  src/manda/convertor.c
  src/manda/parse.c
  src/manda/parse.h
  src/manda/parse_utils.c
Labels: build, feat

#11 Fix: 파서 오류수정 및 기능추가#10
  .gitignore
  lib/libft/libft.h
  src/manda/parse.c
  src/manda/parse.h
  src/manda/split.c
  src/manda/split_utils.c
Labels: fix

#12 fix: 카메라 구조체 타입 변경 및 파싱 오류 수정
  src/manda/Makefile
  src/manda/convertor.c
  src/manda/include/rt_struct.h
  src/manda/parse_utils.c
Labels: fix

#15 feat: 오브젝트 판별식 수정 및 hit record 반영
  src/manda/Makefile
  src/manda/include/minirt.h
  src/manda/include/rt_struct.h
  src/manda/parse/convertor.c
  src/manda/parse/parse_utils.c
  src/manda/render/Makefile
  src/manda/render/calc.c
  src/manda/render/hit.c
  src/manda/render/hit_cylinder.c
Labels: build, feat, refactor

#16 [feat] 난반사 구현
  scenes/rttest.rt
  scenes/subject.rt
  src/manda/include/rt_struct.h
  src/manda/mlx.c
  src/manda/render/hit.c
  src/manda/render/hit_cylinder.c
  src/manda/render/ray.c
  src/manda/render/render.c
Labels: feat

#18 feat: 입력값 검증 및 에러처리
  src/manda/include/rt_struct.h
  src/manda/parse/Makefile
  src/manda/parse/constructor.c
  src/manda/parse/constructor2.c
  src/manda/parse/convertor.c
  src/manda/parse/parse.h
  src/manda/parse/validate.c
Labels: feat
